"""
Synthetic cell batch generator with labeled degradation modes.
"""

import numpy as np
from config import params as P
from core.physics_engine import simulate_cell_response
from core.virtual_daq import VirtualDAQ


class CellDatabase:
    """
    Generates a synthetic dataset of battery cells with various degradation modes.
    Each cell is characterized by its SOC and degradation mode, and we simulate
    its response to an excitation pulse.
    """

    def __init__(self):
        self.daq = VirtualDAQ()
        self.degradation_modes = [
            'healthy',
            'li_plating',
            'active_material_loss',
            'electrolyte_decomposition',
            'gas_generation',
            'internal_short'
        ]
        self.mode_to_label = {mode: idx for idx, mode in enumerate(self.degradation_modes)}

    def generate_cell_sample(self, soc, degradation_mode, add_noise=True):
        """
        Generate a single sample (one excitation cycle) for a cell with given SOC and degradation mode.
        Returns a dictionary containing the processed signals and the label.
        """
        # Simulate the cell's response
        raw_response = simulate_cell_response(soc, degradation_mode, add_noise=add_noise)
        # Process through the virtual DAQ
        processed_response = self.daq.process_cycle(raw_response)

        # Extract features for ML (we'll use the processed signals directly, but we can also extract features)
        # For simplicity, we'll use the raw processed signals as input to the ML model.
        # We'll also return the label and SOC.

        # Label: degradation mode index
        label = self.mode_to_label[degradation_mode]

        # We'll also return the SOC for potential use (though not used as label in this simulation)
        sample = {
            'electrical': processed_response['electrical'],
            'ultrasonic': processed_response['ultrasonic'],
            'thermal': processed_response['thermal'],
            'degradation_mode': label,
            'soc': soc,
            'raw_response': raw_response  # optional, for debugging
        }

        return sample

    def generate_batch(self, batch_size, soc_range=(0.0, 1.0), degradation_mode_dist=None):
        """
        Generate a batch of cell samples.
        batch_size: number of samples to generate
        soc_range: tuple (min, max) for SOC distribution (uniform)
        degradation_mode_dist: list of probabilities for each degradation mode (must sum to 1).
                               If None, uniform distribution.
        Returns:
            A list of samples (each sample is a dictionary as generated by generate_cell_sample)
        """
        if degradation_mode_dist is None:
            degradation_mode_dist = [1.0 / len(self.degradation_modes)] * len(self.degradation_modes)
        assert len(degradation_mode_dist) == len(self.degradation_modes)
        assert abs(sum(degradation_mode_dist) - 1.0) < 1e-6

        samples = []
        for _ in range(batch_size):
            # Sample SOC uniformly in the given range
            soc = np.random.uniform(soc_range[0], soc_range[1])
            # Sample degradation mode according to the distribution
            mode_idx = np.random.choice(len(self.degradation_modes), p=degradation_mode_dist)
            degradation_mode = self.degradation_modes[mode_idx]
            # Generate the sample
            sample = self.generate_cell_sample(soc, degradation_mode, add_noise=True)
            samples.append(sample)

        return samples

    def generate_labeled_dataset(self, num_samples, soc_range=(0.0, 1.0)):
        """
        Generate a labeled dataset for training.
        Returns:
            X_electrical: list of electrical signals (each is a dict or we can flatten)
            X_ultrasonic: list of ultrasonic signals
            X_thermal: list of thermal signals
            y_degradation: list of degradation mode labels (integers)
            y_soh: list of SOH values (we'll compute SOH as 100 * SOC for simplicity? Actually SOH is capacity-related, not directly SOC.
                   We'll simulate SOH as decreasing with degradation and usage. For simplicity, we'll set:
                   SOH = 100 * (1 - degradation_severity) * soc? This is not accurate.
                   Instead, we'll assume that the SOC is the current state of charge, and the SOH is the maximum capacity relative to nominal.
                   We'll generate SOH independently: healthy cells have SOH=100%, degraded cells have lower SOH.
                   We'll link SOH to degradation mode and add some variability.
            )
        """
        # We'll generate samples and then extract the signals and labels.
        samples = self.generate_batch(num_samples, soc_range=soc_range, degradation_mode_dist=None)

        # Initialize lists
        X_electrical = []
        X_ultrasonic = []
        X_thermal = []
        y_degradation = []
        y_soh = []

        # Define SOH mapping for each degradation mode (with some variability)
        # Base SOH for each mode (percentage)
        soh_base = {
            'healthy': 95.0,  # healthy cells might have slight variations
            'li_plating': 85.0,
            'active_material_loss': 80.0,
            'electrolyte_decomposition': 82.0,
            'gas_generation': 90.0,  # gas generation might not affect capacity as much
            'internal_short': 70.0
        }

        for sample in samples:
            # We'll use the processed signals as features.
            # For the ML model, we want sequences. We'll use the voltage signal for electrical,
            # the ultrasonic signal (the waveform) for ultrasonic, and the temperature rise for thermal.
            # We'll extract the signals from the processed dictionary.

            # Electrical: use voltage signal
            elec_signal = sample['electrical']['voltage']
            X_electrical.append(elec_signal)

            # Ultrasonic: use the simulated signal (the waveform)
            ultra_signal = sample['ultrasonic']['signal']
            X_ultrasonic.append(ultra_signal)

            # Thermal: use temperature rise signal
            thermal_signal = sample['thermal']['temperature_rise']
            X_thermal.append(thermal_signal)

            # Degradation label
            y_degradation.append(sample['degradation_mode'])

            # SOH: we'll compute based on degradation mode and add some noise
            mode = self.degradation_modes[sample['degradation_mode']]
            base_soh = soh_base[mode]
            # Add some variability based on SOC? Actually, SOH is independent of SOC (it's the capacity fade).
            # We'll add Gaussian noise to the SOH.
            soh = base_soh + np.random.normal(0, 2.0)  # 2% standard deviation
            # Clamp to reasonable values
            soh = np.clip(soh, 0, 100)
            y_soh.append(soh)

        return X_electrical, X_ultrasonic, X_thermal, y_degradation, y_soh